import { React, useEffect, useMemo, useState, api, unwrap, fmtMoney, fmtQty, fmtDate, today, getError, Logo, Button, Modal, Toast, Field, EmptyState, Pagination, DataTable, StatusBadge, AlertTriangle, Archive, ArrowDownToLine, ArrowUpFromLine, BarChart3, Bell, Boxes, Check, ChevronDown, CircleDollarSign, ClipboardCheck, Eye, EyeOff, FileDown, FileText, Gauge, History, Layers3, LogOut, Menu, Package, Pencil, Plus, RefreshCw, Search, Settings, ShieldCheck, SlidersHorizontal, Trash2, Truck, UserCog, Users, Warehouse, X, Bar, BarChart, CartesianGrid, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "../shared.jsx";
import { PageHeader } from "../layout.jsx";
import { useList } from "./listing.jsx";
export function InventoriesPage({ me, notify }) {
  const list = useList("inventories/"); const [categories, setCategories] = useState([]); const [form, setForm] = useState(null); const [detail, setDetail] = useState(null);
  useEffect(() => { api.get("categories/?page_size=200").then((r) => setCategories(unwrap(r.data))); }, []);
  async function create(e) { e.preventDefault(); try { await api.post("inventories/", { ...form, category: form.category || null, populate: true }); notify("Inventário iniciado."); setForm(null); list.reload(); } catch (err) { notify(getError(err), "error"); } }
  async function open(row) { const r = await api.get(`inventories/${row.id}/`); setDetail(r.data); }
  async function saveItem(item, counted, justification) { try { await api.post(`inventories/${detail.id}/add_item/`, { product: item.product, counted_quantity: counted, justification }); await open(detail); notify("Contagem atualizada."); } catch (err) { notify(getError(err), "error"); } }
  async function invAction(name) { try { await api.post(`inventories/${detail.id}/${name}/`); notify("Inventário atualizado."); setDetail(null); list.reload(); } catch (err) { notify(getError(err), "error"); } }
  return <><PageHeader title="Inventários" description="Conferência física, sobras, faltas, justificativas e ajustes controlados." actions={<Button icon={Plus} onClick={() => setForm({ category: "", notes: "" })}>Novo inventário</Button>} />
    <section className="panel"><DataTable loading={list.loading} rows={list.rows} columns={[{ key: "number", label: "Número", render: (r) => <button className="table-link" onClick={() => open(r)}>{r.number}</button> }, { key: "started_at", label: "Início", render: (r) => fmtDate(r.started_at) }, { key: "category_name", label: "Categoria" }, { key: "items", label: "Produtos", render: (r) => r.items?.length || 0 }, { key: "divergences_count", label: "Divergências", render: (r) => r.divergences_count ?? r.items?.filter((i) => Number(i.difference) !== 0).length ?? 0 }, { key: "status", label: "Situação", render: (r) => <StatusBadge value={r.status} label={{ OPEN: "Em andamento", WAITING: "Aguardando confirmação", DONE: "Concluído", CANCELLED: "Cancelado" }[r.status]} /> }, { key: "user_name", label: "Responsável" }]} /></section>
    {form && <Modal title="Iniciar inventário" onClose={() => setForm(null)}><form className="form-grid" onSubmit={create}><Field label="Categoria"><select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}><option value="">Todos os produtos</option>{categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Observações"><textarea value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></Field><div className="form-actions full"><Button>Iniciar conferência</Button></div></form></Modal>}
    {detail && <Modal title={`Inventário ${detail.number}`} onClose={() => setDetail(null)} size="xl"><div className="inventory-detail"><div className="summary-line"><StatusBadge value={detail.status} /><span>{detail.items.length} produtos</span></div><div className="table-wrap"><table><thead><tr><th>Produto</th><th>Registrado</th><th>Contado</th><th>Divergência</th><th>Justificativa</th><th>Ação</th></tr></thead><tbody>{detail.items.map((item) => <InventoryItemRow key={item.id} item={item} disabled={!['OPEN','WAITING'].includes(detail.status)} onSave={saveItem} />)}</tbody></table></div><div className="form-actions">{detail.status === "OPEN" && <Button variant="secondary" onClick={() => invAction("submit")}>Enviar para confirmação</Button>}{detail.status === "WAITING" && me.permissions.is_admin && <Button onClick={() => invAction("conclude")}>Concluir e ajustar divergências</Button>}{detail.status !== "DONE" && <Button variant="danger" onClick={() => invAction("cancel")}>Cancelar inventário</Button>}</div></div></Modal>}
  </>;
}
export function InventoryItemRow({ item, disabled, onSave }) { const [counted, setCounted] = useState(item.counted_quantity); const [justification, setJustification] = useState(item.justification || ""); const diff = Number(counted || 0) - Number(item.system_quantity || 0); return <tr><td><strong>{item.product_name}</strong><small className="block">{item.product_code}</small></td><td>{fmtQty(item.system_quantity)}</td><td><input className="table-input" type="number" min="0" step="0.001" disabled={disabled} value={counted} onChange={(e) => setCounted(e.target.value)} /></td><td><StatusBadge value={diff === 0 ? "normal" : diff > 0 ? "warning" : "danger"} label={fmtQty(diff)} /></td><td><input className="table-input" disabled={disabled} value={justification} onChange={(e) => setJustification(e.target.value)} /></td><td>{!disabled && <button className="icon-btn success" onClick={() => onSave(item, counted, justification)}><Check size={16} /></button>}</td></tr>; }
