import { React, useEffect, useMemo, useState, api, unwrap, fmtMoney, fmtQty, fmtDate, today, getError, Logo, Button, Modal, Toast, Field, EmptyState, Pagination, DataTable, StatusBadge, AlertTriangle, Archive, ArrowDownToLine, ArrowUpFromLine, BarChart3, Bell, Boxes, Check, ChevronDown, CircleDollarSign, ClipboardCheck, Eye, EyeOff, FileDown, FileText, Gauge, History, Layers3, LogOut, Menu, Package, Pencil, Plus, RefreshCw, Search, Settings, ShieldCheck, SlidersHorizontal, Trash2, Truck, UserCog, Users, Warehouse, X, Bar, BarChart, CartesianGrid, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "../shared.jsx";
import { PageHeader } from "../layout.jsx";
import { useList } from "./listing.jsx";
export function UsersPage({ notify }) {
  const list = useList("users/"); const [form, setForm] = useState(null);
  async function save(e) { e.preventDefault(); try { const payload = { username: form.username, email: form.email, first_name: form.first_name || "", last_name: form.last_name || "", is_active: form.is_active, full_name: form.full_name, cpf: form.cpf || null, phone: form.phone, position: form.position, role: form.role, profile_active: form.profile_active, ...(form.password ? { password: form.password } : {}) }; if (form.id) await api.put(`users/${form.id}/`, payload); else await api.post("users/", payload); notify("Usuário salvo."); setForm(null); list.reload(); } catch (err) { notify(getError(err), "error"); } }
  function edit(r) { setForm({ id: r.id, username: r.username, email: r.email, first_name: r.first_name, last_name: r.last_name, is_active: r.is_active, full_name: r.profile?.full_name || "", cpf: r.profile?.cpf || "", phone: r.profile?.phone || "", position: r.profile?.position || "", role: r.profile?.role || "OPERATOR", profile_active: r.profile?.active ?? true, password: "" }); }
  return <><PageHeader title="Usuários e permissões" description="Administradores e operadores com controle de acesso no front-end e no back-end." actions={<Button icon={Plus} onClick={() => setForm({ username: "", email: "", first_name: "", last_name: "", is_active: true, full_name: "", cpf: "", phone: "", position: "", role: "OPERATOR", profile_active: true, password: "" })}>Novo usuário</Button>} />
    <section className="panel"><DataTable loading={list.loading} rows={list.rows} columns={[{ key: "username", label: "Usuário" }, { key: "profile", label: "Nome completo", render: (r) => r.profile?.full_name }, { key: "email", label: "E-mail" }, { key: "role", label: "Perfil", render: (r) => <StatusBadge value={r.profile?.role} label={r.profile?.role === "ADMIN" ? "Administrador" : "Operador"} /> }, { key: "position", label: "Cargo", render: (r) => r.profile?.position }, { key: "is_active", label: "Situação", render: (r) => <StatusBadge value={r.is_active && r.profile?.active ? "active" : "inactive"} label={r.is_active && r.profile?.active ? "Ativo" : "Inativo"} /> }, { key: "last_login", label: "Último acesso", render: (r) => fmtDate(r.last_login) }, { key: "actions", label: "Ações", render: (r) => <button className="icon-btn" onClick={() => edit(r)}><Pencil size={16} /></button> }]} /></section>
    {form && <Modal title={form.id ? "Editar usuário" : "Novo usuário"} onClose={() => setForm(null)} size="lg"><form className="form-grid cols-2" onSubmit={save}>{[["full_name","Nome completo",true],["cpf","CPF"],["phone","Telefone"],["email","E-mail"],["username","Nome de usuário",true],["position","Cargo"],["password",form.id ? "Nova senha (opcional)" : "Senha",!form.id]].map(([key,label,required]) => <Field key={key} label={label} required={required}><input type={key === "password" ? "password" : key === "email" ? "email" : "text"} value={form[key] || ""} onChange={(e) => setForm({ ...form, [key]: e.target.value })} required={required} minLength={key === "password" ? 8 : undefined} /></Field>)}<Field label="Perfil"><select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })}><option value="ADMIN">Administrador</option><option value="OPERATOR">Operador de estoque</option></select></Field><Field label="Situação"><select value={String(form.is_active && form.profile_active)} onChange={(e) => setForm({ ...form, is_active: e.target.value === "true", profile_active: e.target.value === "true" })}><option value="true">Ativo</option><option value="false">Inativo</option></select></Field><div className="form-actions full"><Button>Salvar usuário</Button></div></form></Modal>}
  </>;
}
